### ISSUE TITLE
Could you release d4rl-v2 pre-trained offline models?

### ISSUE THREAD

**Issue by HYDesmondLiu** [shlee94/Off2OnRL#2]
d4rl-v0 is known for bugs, people tend to use d4rl-v2 as the standard.
Could you release the pre-trained models for d4rl-v2?

**Comment by HYDesmondLiu** [comment]
Forget about it.

**Comment by George-Chia** [comment]
> 

hahaha why?

**Comment by HYDesmondLiu** [comment]
hahaha why not?
