### ISSUE TITLE
Was it possible to release the code for Fig.1(a)

### ISSUE THREAD

**Issue by nuomizai** [shlee94/Off2OnRL#3]
Hi, this paper is very instructive. I would like to know more about the log-likelihood in Fig. 1(a) in original paper. Was it possible to release the corresponding code or to provide some detail computation process about that?

**Comment by linhlpv** [comment]
Hi @nuomizai and @shlee94 
I also would like to know more about how to create the figure 1. Have you successfully implemented the code for it? Could you help me about this? 
Thank you so much.
